# Generated by Django 3.1.4 on 2021-01-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210102_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
