# Generated by Django 3.1.4 on 2021-01-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210102_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='desc',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_url',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
