# Generated by Django 3.1.4 on 2021-01-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210102_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='country',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='url',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
