# Generated by Django 3.1.4 on 2021-01-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210102_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_list', models.TextField(unique=True)),
            ],
        ),
    ]
