# Generated by Django 3.1.4 on 2021-01-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_countrylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylist',
            name='country_list',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='url',
            field=models.TextField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
