# Generated by Django 3.1.4 on 2021-01-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210104_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_count', models.TextField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='CountryList',
        ),
    ]
