# Generated by Django 3.1.4 on 2021-01-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_home_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, unique=True)),
                ('desc', models.TextField(max_length=2000, unique=True)),
            ],
        ),
    ]
