# Generated by Django 3.1.4 on 2021-01-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210104_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='image_url',
            new_name='image',
        ),
    ]
